---
- name: Create the directory for PostgreSQL key
  file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: '0755'

- name: Import the repository signing key
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    mode: '0644'

- name: Create the repository configuration file
  copy:
    content: "deb
      [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc]
      https://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg
      main\n"
    dest: /etc/apt/sources.list.d/pgdg.list
    mode: '0644'

- name: Update APT package index
  apt:
    update_cache: yes
  ignore_errors: true

- name: Install PostgreSQL and development packages
  apt:
    pkg:
    - postgresql-17
    - postgresql-server-dev-17
    state: present

- name: Create symbolic links for PostgreSQL binaries
  file:
    src: "/usr/lib/postgresql/17/bin/{{ item }}"
    dest: "/usr/sbin/{{ item }}"
    state: link
  loop: "{{ lookup('fileglob', '/usr/lib/postgresql/17/bin/*') }}"
...
