---
- name: Install HAproxy
  apt:
    pkg:
    - haproxy
    state: present
  when:
  - ansible_distribution == 'Ubuntu'
  - ansible_distribution_major_version == '22'

- name: Set HAproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  when:
  - ansible_distribution == 'Ubuntu'
  - ansible_distribution_major_version == '22'
  notify: restart haproxy

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: true
  when:
  - ansible_distribution == 'Ubuntu'
  - ansible_distribution_major_version == '22'
...
